version: "3"
services:
  redis-server:
    image: "redis"
  proxy-server:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./proxy
    ports:
      - "8000:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
<<<<<<< HEAD
    ports:
      - "4001:4000"
=======
>>>>>>> dev
    depends_on:
      - redis-server
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
